services:
  fundbox_checkout.model.order_details:
    class: Fundbox\Bundle\FundboxCheckoutBundle\Model\OrderDetails
    arguments:
      - '@oro_pricing.subtotal_processor.total_processor_provider'
      - '@oro_tax.provider.tax_subtotal'
      - '@oro_currency.rounding.price_rounding_service'
      - '@oro_pricing.provider.matching_price'
      - '@oro_pricing.model.product_price_scope_criteria_request_handler'
      - '@oro_checkout.data_provider.converter.checkout_to_order'
    calls:
      - ['setLogger', ['@logger']]
    tags:
      - { name: monolog.logger, channel: oro_fbx_checkout }